-- Run this in the Supabase SQL Editor (Dashboard → SQL → New query)

create table if not exists public.watchlists (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users (id) on delete cascade,
    stock_symbol text not null,
    created_at timestamptz not null default now(),
    unique (user_id, stock_symbol)
);

alter table public.watchlists enable row level security;

create policy "Users can view their own watchlist"
    on public.watchlists for select
    using (auth.uid() = user_id);

create policy "Users can add to their own watchlist"
    on public.watchlists for insert
    with check (auth.uid() = user_id);

create policy "Users can remove from their own watchlist"
    on public.watchlists for delete
    using (auth.uid() = user_id);

create index if not exists watchlists_user_id_idx on public.watchlists (user_id);
